### ISSUE TITLE
List styling in chat is not nice.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#461]
Make it nice!

**Comment by NikSudan** [comment]
```css
ul {
  padding-left: 20px;
}

ul li {
  margin-bottom: auto;
}
```
